all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
# javac -encoding UTF-8 InformationEstimator_org.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
	javac -encoding UTF-8 FinalTest.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171811/Hello
# java -classpath "../.." s4.B171811/Frequencer
# java -classpath "../.." s4.B171811/InformationEstimator_org
# java -classpath "../.." s4.B171811/InformationEstimator
#	java -classpath "../.." s4.B171811/TestCase
	java -classpath "../.." s4.B171811/FinalTest
